config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  resources :ratings, only: [:create, :update]
  resources :comments, only: [:create, :update]
  resources :tags

  root'pages#home'

  resources :users, only: [:show]

  get '/ingredients/:id', to: 'ingredientes#show' , as: 'ingredient'
  get '/tags/:id', to: 'tags#show'
  get '/recipes/search', to: 'recipes#search'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  #koristi se za show
  attr_accessor :stringIngredients

  belongs_to :user
  has_many :measurements, dependent: :destroy
  has_many :ingredients, through: :measurements
  has_many :ratings

  RECIPE_TITLE_REGEX = /\A[a-zA-Z[čćđšž][ ]]+\z/i

  validates :title, presence: true, format: {with: RECIPE_TITLE_REGEX, message: "Samo slova dopuštena"}
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100" }, :default_url => "/images/:style/default.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	searchable do
		text :title
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:show, :index, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  attr_accessor :measurs, :ingrs


  # GET /recipes
  # GET /recipes.json
  def index
    search_query = params[:search]
    if search_query.blank? || search_query.nil?
      @recipes = Recipe.all
    else
      @recipes = Array.new

      @search = Sunspot.search Recipe, Tag, Ingredient do
        fulltext search_query
      end

      @search.results.each do |result|
        if result.is_a?(Tag)
          @recipe_tags = RecipeTag.select { |rt| rt.tag_id == result.id}

          @recipe_tags.each do |tag|
            Recipe.select { |rc| rc.id == tag.recipe_id }.each do |recipe|
                @recipes << recipe
            end
          end
        elsif result.is_a?(Ingredient)
          @measurements = Measurement.select { |m| m.ingredient_id == result.id }

          @measurements.each do |measurement|
            Recipe.select { |r| r.id == measurement.recipe_id }.each do |recipe|
                @recipes << recipe
            end
          end
        elsif result.is_a?(Recipe)
            @recipes << result
        end
      end
    end
  end
=begin
    @search = Recipe.search do
      fulltext query
    end
    @recipes = @search.results
=end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @rating = Rating.new
    @comments=Comment.all
    @comment = Comment.new
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build

=begin
    MeasuringUnit.create(measure: "kg");
    MeasuringUnit.create(measure: "dg");
    MeasuringUnit.create(measure: "g");
    MeasuringUnit.create(measure: "mg");
    MeasuringUnit.create(measure: "komad(a)");
    MeasuringUnit.create(measure: "l");
    MeasuringUnit.create(measure: "dl");
    MeasuringUnit.create(measure: "cl");
    MeasuringUnit.create(measure: "ml");
    MeasuringUnit.create(measure: "malih žlica");
    MeasuringUnit.create(measure: "velikih žlica");
    MeasuringUnit.create(measure: "čaša");
=end

  end


  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.user = current_user
    @recipe.save
    @measurs = Array.new
    @ingrs = Array.new
    @tgs = Array.new
    #ovo bi trebalo unutar sebe prikupiti sastojke i mjere
    parse_ingredients
    parse_tags
    @recipe.measurements = @measurs
    @recipe.ingredients = @ingrs
    @recipe.recipe_tags = @tgs

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    @measurs = Array.new
    @ingrs = Array.new
    @tgs = Array.new
    #unisti prijasnje mjere(veze medu receptima i sastojcima)!
    @recipe.measurements.destroy
    @recipe.recipe_tags.destroy
    #ovo bi trebalo unutar sebe prikupiti sastojke i mjere
    parse_ingredients
    parse_tags
    @recipe.ingredients = @ingrs
    @recipe.measurements = @measurs
    @recipe.recipe_tags = @tgs

    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :image)
    end

    def parse_ingredients
      line = params.require(:recipe).permit(:ingredients)[:ingredients]
      splitted = line.to_s.split("\r\n")
      splitted.each do |strLine|
        if strLine.starts_with?("{")
          next
        end

        array = strLine.split("\t")
        ingredient = Ingredient.create(name: array[1])
        @ingrs << ingredient
        @measurs << Measurement.create(ingredient: ingredient, recipe: @recipe, measure: array[0].strip)
        Measurement.create(ingredient_id: ingredient.id, recipe_id: @recipe.id, measure: array[0].strip)
     end

    end

    def parse_tags
      line = params.require(:recipe).permit(:tags)[:tags]
      splitted = line.to_s.split("\r\n")
      splitted.each do |strLine|
        if strLine.starts_with?("{")
          next
        end

        tag = Tag.find_or_create_by(title: strLine)
        @tgs << RecipeTag.create(tag: tag, recipe: @recipe)
      end
    end

    def authorize_user!
      redirect_to recipes_path if current_user != @recipe.user && current_user.email != "lovro.kordis@fer.hr"
    end

    def search
      @search = Sunspot.search Recipe, Tag, Ingredient do
        fulltext search_query
      end

      @search.results.each do |result|
        if result.is_a?(Tag)
          @recipe_tags = RecipeTag.select { |rt| rt.tag_id == result.id}

          @recipe_tags.each do |tag|
            Recipe.select { |rc| rc.id == tag.recipe_id }.each do |recipe|
              @recipes << recipe
            end
          end
        elsif result.is_a?(Ingredient)
          @measurements = Measurement.select { |m| m.ingredient_id == result.id }

          @measurements.each do |measurement|
            Recipe.select { |r| r.id == measurement.recipe_id }.each do |recipe|
              @recipes << recipe
            end
          end
        else
          @recipes << result
        end
      end
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: {multipart: true} do |f| %>
    <div class="col-xs-offset-3 col-xs-6 error">
      <% if @recipe.errors.any? %>
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>

            </div>

            <ul>
              <% @recipe.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>


    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <div class="well well-group col-sm-8 col-sm-offset-2">
            <%= f.label :naslov %><br>
            <%= f.text_field :title, class: "form-control", placeholder: "Upišite naziv recepta" %>
          </div>
        </div>
        <div class="form-group">
          <div class="well well-group col-sm-8 col-sm-offset-2">
            <%= f.label :opis %><br>
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Upišite opis izrade recepta" %>
          </div>
        </div>

        <div class="col-sm-8 col-sm-offset-2">
          <ul id="list-group">
            <li id="ingredients-list-title" class="list-group-item"><h3 align="center">Lista sastojaka</h3></li>
          </ul>
        </div>

        <%= f.text_area :ingredients, id: "hidden-area" %>

        <div class="well well-group col-sm-8 col-sm-offset-2">
          <form class="form-inline">

            <p id="Error-label"></p>
            <div class="form-group">
              <label class="sr-only" for="Mjera">Mjera</label>
              <input type="text" class="form-control" id="measure" placeholder="Mjera">
            </div>
            <div class="form-group">
              <label class="sr-only" for="Sastojak">Sastojak</label>
              <input type="text" class="form-control" id="ingredient" placeholder="Sastojak">
            </div>
            <button type="button" id="add-to-list" class="btn btn-success" id="add-ingredient">Dodaj sastojak</button>

            <script>
                document.getElementById("add-to-list").onclick = function () {
                    var list = document.getElementById("list-group");
                    var measure = document.getElementById("measure");
                    var ingredient = document.getElementById("ingredient");
                    var hidden = document.getElementById("hidden-area");

                    var measurementRegex = /^([0-9][ ])*([a-z]|[A-Z]|[čćđšž])+[ ]*$/i;
                    var ingredientRegex = /^([a-z]|[A-Z]|[čćđšž]|[ ])+$/i;


                    if (measure.value.match(measurementRegex)) {

                        if (ingredient.value.match(ingredientRegex)) {
                            document.getElementById("Error-label").innerHTML = "";
                            var newLI = document.createElement("li");
                            var allLi = list.getElementsByTagName("li");
                            if(allLi.length > 1) {
                                for(var i = 1, len = allLi.length; i<len; i++) {
                                    var allP = allLi[i].getElementsByTagName("span");
                                    if(allP[0].id === ingredient.value) {
                                        document.getElementById("Error-label").innerHTML = "GREŠKA! Sastojak \"" + ingredient.value + "\" već postoji";
                                        measure.value = "";
                                        ingredient.value = "";
                                        return;
                                    }
                                }
                            }

                            var input = measure.value + "\t" + ingredient.value;
                            var inputSpanTag = document.createElement("span");
                            inputSpanTag.innerHTML = input;
                            inputSpanTag.id = ingredient.value;

                            newLI.appendChild(inputSpanTag);
                            newLI.className = newLI.className + "list-group-item show";

                            var newButton = document.createElement("input");
                            newButton.type = "button";
                            newButton.value = "Ukloni";
                            newButton.className = "btn btn-danger delete-ingredient";
                            newButton.style.textAlign = "center";
                            newButton.onclick = function () {
                                list.removeChild(newLI);
                            }

                            newLI.appendChild(newButton)
                            list.appendChild(newLI);
                            measure.value = "";
                            ingredient.value = "";

                        } else {
                            document.getElementById("Error-label").innerHTML = "GREŠKA! Sastojak \"" + ingredient.value + "\" nije dobro unesen. Pokušajte ponovo!"
                            ingredient.value = "";
                        }

                    } else {
                        document.getElementById("Error-label").innerHTML = "GREŠKA! Mjera \"" + measure.value + "\" nije dobro unesena. Pokušajte ponovo!"
                        measure.value = "";
                    }
                }
            </script>
          </form>
        </div>

        <div class="form-group">
          <div class="well well-group col-sm-4 col-sm-offset-2">
            <%= f.label :slika %><br>
            <%= f.file_field :image, accept: "image/*", class: "form-control-file", placeholder: "Dodajte sliku" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-5 col-sm-2 create-recipe">
            <%= f.submit "Izradi recept", class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/recipes/_rating_input.html.erb
<%= form_for @rating do |f| %>

	<% if(Rating.where(:user_id => current_user, :recipe_id => @recipe.id).length > 0) %>
		<h4><%= "Vaša ocjena: " %> <%= Rating.where(:user_id => current_user, :recipe_id => @recipe.id).first.rating.to_s %></h4><br></br>
	<% end %>

	<%= f.select :rating, [['5'],['4'],['3'],['2'],['1']], {}, {class: 'form-control rating-input'} %>


	<div class="field">
	    <%= f.hidden_field :recipe_id, :value => @recipe.id %>
	</div>

	<div class="actions">
	    <%= f.submit "Dodaj ocjenu" , class: "btn btn-secondary" %>
	</div>

<% end%>

app/views/recipes/_recipe.html.erb
<!DOCTYPE html>
<html lang="en">

  <body>
    <!-- Page Content -"->
    <!div class="row">-"->
      <!% obj.each do |recipe| %>--">
          <div class="col-xs-offset-3 col-xs-6">
            <div class="well">
              <!%= link_to (image_tag recipe.image.url(),height: '100', width: '100', class: 'image img-circle'), recipe %> -"->
              <strong id = "recipe_title"><!%= recipe.title %></strong>
            </div>
          </div>
      <!% end %>
    </div> -->
    <div class="container">
      <div class="row">
        <% obj.each do |recipe| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail polje-recept">
              <%= link_to (image_tag recipe.image.url(),height: '200', width: '400', class: 'image img-circle'), recipe %>
              <div class="caption">
                <h3 class="polje-naslov"><%= recipe.title %></h3>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/recipes/index.html.erb
<%= render 'recipe', obj: @recipes%>

app/views/recipes/show.html.erb
<div class = "alert">
	<a onclick="goBack()" class = "close close-login" data-dismiss="alert">&#215;</a>

	<script>
      function goBack() {
          window.history.back();
      }
	</script>

	<div class="panel panel-default show-panel">
		<div class="panel-body">
			<div class="row">
				<div class="col-md-offset-1 col-md-10">
					<div align="center">
						<%= image_tag @recipe.image.url(), class: "img-circle" ,height: '500', width: '500' %>
					</div>
					<div class="table-responsive">
						<table class="table">
							<body>
							<tr>
								<td><strong>Naslov:</strong></td>
								<td><h3><%= @recipe.title %></h3></td>
							</tr>
							<tr>
								<td><strong>Izradio:</strong></td>
								<td><strong><%= @recipe.user.email %> </strong></td>
							</tr>
							<tr>
								<td><strong>Datuma:</strong></td>
								<td><%= @recipe.created_at.strftime(" %d.%m.%Y")%> <%= @recipe.created_at.strftime("u %I:%M%p")%> </td>
							</tr>
							<tr>
								<td><strong>Opis:</strong></td>
								<td><pre class = "pre-recipe"><%= @recipe.description %></pre></td>
							</tr>
							<tr>
								<td><strong>Sastojci:</strong></td>
								<td>
									<table class="table table-striped">
										<tr>
											<td><strong>Mjera sastojka</strong></td>
											<td><strong>Naziv sastojka</strong></td>
										</tr>
										<% @recipe.measurements.each do |m|%>
												<tr>
													<td><%=m[:measure]%></td>
													<td><%= link_to m.ingredient[:name], ingredient_path(m.ingredient), class: "ingredient-link"%></td>
												</tr>
										<% end %>
									</table>

								</td>
							</tr>
							<tr>
								<td><strong>Oznake:</strong></td>
									<td>
										<% @recipe.recipe_tags.each do |t| %>
											<%= link_to '#' + Tag.find(t[:tag_id]).title.strip, tag_path(t.tag.id), class: "btn btn-info" %>
										<% end %>
									</td>
							</tr>
							</body>
						</table>
						<% if current_user.present? && current_user.id == @recipe.user_id || current_user.email == "lovro.kordis@fer.hr" %>
								<div align = "center">
									<%= link_to 'Uredi', edit_recipe_path(@recipe), class: "btn btn-lg btn-primary" %>
									<%= link_to 'Izbriši', recipe_path(@recipe), method: :delete, class: "btn btn-lg btn-danger", data: { confirm: "Jeste li sigurni da želite obrisati recept?"}%>
								</div>
						<% end %>


					</div>
				</div>
			</div><br>
			<div class="form-group" align="center">
				<% if (Rating.where(:recipe_id => @recipe.id).length != 0) %>
	          <div class="">
	          	<h3><%= "Prosječna ocjena: " %><%= @recipe.average_rating %></h3><br></br>
	          </div>
	      <% end %>

	      <% if current_user.present? %>
	          <% if (Rating.where(:recipe_id => @recipe.id).length == 0) %>
								<div class="">
									<h2><%= "Dodajte prvu ocjenu" %></h2><br></br>
								</div>
	          <% end %>
	          <%= render 'rating_input' %>
	      <% end %>
			</div>

			<h3> Komentari: </h3>
			<div class="form-group" align="left">
				<ul class="reviews-list">
					<% @comments.each do |c|%>
		          <%if (c.recipe_id == @recipe.id )%>
								<li class="reviews-list-item">
									<blockquote class="blockquote">
										<p class="mb-0">
											<%= c.user_email.to_s %><%= ": "%>
											<%= c.comment.to_s %>
										</p>
									</blockquote>
								</li>
		          <% end %>
		      <% end %>
				</ul>
			</div>
			<div class="form-group" align="left">
	      <% if current_user.present? %>
	          <%= form_for @comment do |f| %>
	              <div class="field">
	                <%= f.label :Komentar , id: "hidden-area" %><br>
	                <%= f.text_area :comment ,class: "comment-input" %>
	                <%= f.hidden_field :recipe_id, :value => @recipe.id %>
	              </div>

	              <div class="">
	                <%= f.submit "Dodaj komentar" ,class: " btn" %>
	              </div>
	          <% end %>
	      <% end %>
			</div>
    </div>
	</div>
</div>