config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  resources :ratings, only: [:create, :update]
  resources :comments, only: [:create, :update]
  resources :tags

  root'pages#home'

  resources :users, only: [:show]

  get '/ingredients/:id', to: 'ingredientes#show' , as: 'ingredient'
  get '/tags/:id', to: 'tags#show'
  get '/recipes/search', to: 'recipes#search'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-admin">
				<span class="sr-only">Toggle Menu</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand"><%= link_to "Online Kuhača", root_path, class: "navbar-brand", id: "logo" %> </a>

		</div><!--/.navbar-header -->

		<div class="collapse navbar-collapse">



			<ul class="nav navbar-nav navbar-right">
				<li class="hidden-sm hidden-xs">

					<% if !user_signed_in? %>
					<%= link_to "Prijava", new_user_session_path, class: "navbar-brand" %>
					<% else %>
					<%= link_to current_user.email, user_path(current_user.id), class: "navbar-brand", id: "username"%>
					<%= link_to "Odjava", destroy_user_session_path, class: "navbar-brand" %>

					<% end %>
				</li>
			</ul>


			<div class="navbar-form navbar-left" role="search">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon"><span class="glyphicon glyphicon-search"></span></span>
					<div class="form-group">
						<%= form_tag '/recipes', :method => :get do %>
		    			<%= text_field_tag :search, params[:search], placeholder:"Pretraži recepte", class: "form-control" %>
		    			<%= submit_tag "Traži", :name => nil, :class => "btn btn-success", :id => "navbar-potvrdi" %>
		    		<% end %>
	   			</div>

	    		<%=link_to "Svi recepti", recipes_path, class: "btn btn-success" %>
	    		<% if user_signed_in? %>

	    		<%=link_to"Dodaj recept", new_recipe_path, class: "btn btn-success" %>

	    		<% end %>
    		</div>
    	</div>


    </div><!--/.container-->
</nav><!--/.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineKuhaca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<%= yield %>

	<!--
<div class = "col-xs-12">
	<!%= debug(params) if Rails.env.development? %>
</div>
-->





</body>
</html>